F.F                                                                      [100%]
=================================== FAILURES ===================================
_____________________________ TestClass.test_func ______________________________

self = <test_demo.TestClass object at 0x10f55f828>

    def test_func(self):
        print('测试')
>       assert self.func(3) == 5
E       assert 4 == 5
E         -4
E         +5

test_demo.py:11: AssertionError
----------------------------- Captured stdout call -----------------------------
测试
______________________________ TestClass.test_two ______________________________

self = <test_demo.TestClass object at 0x10f67ef60>

    def test_two(self):
        x = "hello"
>       assert hasattr(x, 'check')
E       AssertionError: assert False
E        +  where False = hasattr('hello', 'check')

test_demo.py:19: AssertionError
- generated html file: /Users/liqhe/PycharmProjects/Python/Pytest/result.html --
2 failed, 1 passed in 0.09 seconds
